
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfilepath: '**/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker info
        docker build -t aspnetapp -f Dockerfile .
        docker login --username=pinaki.best@gmail.com --password=8fe0c4d9-c792-4685-8d42-fa264e504f10 registry.heroku.com
        docker tag aspnetapp registry.heroku.com/warfser/web
        docker push registry.heroku.com/warfser/web
        heroku container:release web --app warfser

   


